version: "3.8"
services:

    db:
        image: mysql:latest
        container_name: todo_app_db
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev
            # dev:
            #     ipv4_address: 10.5.0.5

    phpmyadmin:
        image: phpmyadmin
        container_name: todo_app_phpmyadmin
        depends_on:
            - db
        ports:
            - 8042:80
        environment:
            PMA_HOST: db
        networks:
            - dev
            # dev:
            #     ipv4_address: 10.5.0.6

    maildev:
        image: maildev/maildev
        container_name: todo_app_maildev
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
          - "8041:80"
        networks:
            - dev

    todo_api:
        build: .docker
        container_name: todo_app_api
        ports:
          - "8040:80"
        volumes:
            - ./.docker/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
            - ./.docker/init.sh:/var/www/init.sh
        restart: unless-stopped
        depends_on:
            - db
            - phpmyadmin
            - maildev
        links:
            - db
        networks:
            - dev
            # dev:
            #     ipv4_address: 10.5.0.8

networks:
    dev:
        # driver: bridge
        # ipam:
        #     config:
        #        - subnet: 10.5.0.0/16
        #          gateway: 10.5.0.1

volumes:
    db-data:
