version: "3.8"
services:

    db:
        image: mysql
        container_name: todo_app_db
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: todo_app_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8042:80
        environment:
            PMA_HOST: db
        networks:
            - dev

    maildev:
        image: maildev/maildev
        container_name: todo_app_maildev
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
          - "8041:80"
        restart: always
        networks:
            - dev

    todo_api:
        build: .docker
        container_name: todo_app_api
        ports:
          - "8040:80"
        volumes:
            - ./.docker/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev

networks:
    dev:

volumes:
    db-data:
